networks:
    nginx-phpfpm-postgre:

services:

    # postgres
    db:
        container_name: db
        image: 'postgres:latest'
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
            POSTGRES_DB: db
        volumes:
            - ./db-data/:/var/lib/postgresql/data/
        ports:
            - 5432:5432
        networks:
            - nginx-phpfpm-postgre

    # php-fpm
    php-fpm:
        container_name: php-fpm
        build:
            context: .
            dockerfile: ./php-fpm/Dockerfile
        depends_on:
            - db
        environment:
            - APP_ENV=${APP_ENV}
        volumes:
            - ../app:/var/www
        networks:
            - nginx-phpfpm-postgre

    # nginx
    nginx:
        container_name: nginx
        build:
            context: .
            dockerfile: ./nginx/Dockerfile
        volumes:
            - ../app:/var/www
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/sites/:/etc/nginx/sites-available
            - ./nginx/conf.d/:/etc/nginx/conf.d
            - ./logs:/var/log
        depends_on:
            - php-fpm
        ports:
            - 80:80
            - 443:443
        networks:
            - nginx-phpfpm-postgre



