networks:
    nginx-phpfpm-postgre:

services:

    php-fpm:
        container_name: php-fpm
        build:
            context: .
            dockerfile: ./php-fpm/Dockerfile
        depends_on:
            - database
        volumes:
            - ../api:/var/www
        networks:
            - nginx-phpfpm-postgre

    nginx:
        container_name: nginx
        build:
            context: .
            dockerfile: ./nginx/Dockerfile
        volumes:
            - ../api:/var/www
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/sites/:/etc/nginx/sites-available
            - ./nginx/conf.d/:/etc/nginx/conf.d
            - ./logs:/var/log
        depends_on:
            - php-fpm
        ports:
            - 80:80
            - 443:443
        networks:
            - nginx-phpfpm-postgre

    database:
        image: 'postgres:latest'
        restart: always
        environment:
            POSTGRES_USER: marketPlaceUser
            POSTGRES_PASSWORD: F00D0M1RK3T
            POSTGRES_DB: marketplace
        volumes:
            - ./db-data/:/var/lib/postgresql/data/
        ports:
            - 5432:5432

volumes:
    db-data:

